### ISSUE TITLE
i am getting key error 'file' in send_report_to_slack function.

### ISSUE THREAD

**Issue by irtezakhan** [ToghrulMirzayev/pytest-pyreport#8]

**Comment by ToghrulMirzayev** [comment]
Hi @irtezakhan Could you please tell me how you run pytest? It is mandatory to pass the "webhook URL", "channel ID", and "bot token", otherwise you won't be able to publish the report to Slack chat.

**Comment by bobvork** [comment]
I'm getting the same error. I'll post some more info here to hopefully help anyone else getting the same error, and update when I find out what's going wrong.
I'm using the suggested command from the readme to post to slack. I'm pretty sure I have the right webhook URL and channel ID, but slack is changing the way they integrate things so I'm not entirely sure which token to use. 
I tried the deprecated verification token, the client secret and the signing secret and they all give me the same result.

I'm using `uv`, so this is the command I'm running:
```
uv run pytest --junitxml=result.xml -o junit_family="xunit1" --pyreport --slack-pyreport https://hooks.slack.com/services/.../.../... --chanel-id-- --secret--
```

This is the stack trace I'm getting:

```sh
 [100%] | 
 +---------------------------------+ |
 | | HTML Report generation complete | |
 | |        2024-12-10 09:51         | |
 | +---------------------------------+ |
Traceback (most recent call last):
  File "[..redacted..]/.venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
             ~~~~~~~~~~~~^^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/_pytest/config/__init__.py", line 201, in console_main
    code = main()
  File "[..redacted..]/.venv/lib/python3.13/site-packages/_pytest/config/__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "[..redacted..]/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "[..redacted..]/.venv/lib/python3.13/site-packages/_pytest/main.py", line 330, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "[..redacted..]/.venv/lib/python3.13/site-packages/_pytest/main.py", line 318, in wrap_session
    config.hook.pytest_sessionfinish(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        session=session, exitstatus=session.exitstatus
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "[..redacted..]/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/_pytest/logging.py", line 868, in pytest_sessionfinish
    return (yield)
            ^^^^^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/_pytest/terminal.py", line 893, in pytest_sessionfinish
    result = yield
             ^^^^^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 122, in _multicall
    teardown.throw(exception)  # type: ignore[union-attr]
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/_pytest/warnings.py", line 141, in pytest_sessionfinish
    return (yield)
            ^^^^^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "[..redacted..]/.venv/lib/python3.13/site-packages/pytest_pyreport/plugin.py", line 183, in pytest_sessionfinish
    send_report_to_slack(webhook_url=webhook, channel=channel, bot_token=slack_bot_token)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[..redacted..]/.venv/lib/python3.13/site-packages/pytest_pyreport/plugin.py", line 238, in send_report_to_slack
    file_url = response.json()["file"]["url_private"]
               ~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'file'
```
